# The synthetic biomarker study (#2): three tables and the list of planted
# effects, generated by the seeded script data-raw/synthetic-study.R and shipped
# as package data and as CSV files under inst/extdata/.
#
# The truth every test below asserts against is read from Synthetic_Truth, the
# generator's own parameter list, never typed here a second time.

chrKey <- function(dfData, chrCols) {
  do.call(paste, c(unname(as.list(dfData[chrCols])), sep = "\r"))
}

strHelpText <- function(strTopic) {
  lRd <- if (bSourceTree()) {
    tools::Rd_db(dir = strSourceRoot())
  } else {
    tools::Rd_db("gsm.bio")
  }
  paste(as.character(lRd[[paste0(strTopic, ".Rd")]]), collapse = "")
}

test_that("the three tables load from the package with the documented columns (#2)", {
  expect_identical(
    vapply(Synthetic_Results, function(x) class(x)[1], character(1)),
    c(
      USUBJID = "character", VISIT = "character", VISITNUM = "integer",
      TEST = "character", STRESU = "character", STRESN = "numeric"
    )
  )
  expect_identical(
    vapply(Synthetic_Participants, function(x) class(x)[1], character(1)),
    c(
      USUBJID = "character", ARM = "character", SEX = "character",
      AGE = "integer", BMIBL = "numeric", RESPONSE = "character"
    )
  )
  expect_identical(
    vapply(Synthetic_Outcomes, function(x) class(x)[1], character(1)),
    c(
      USUBJID = "character", PARAMCD = "character", PARAM = "character",
      AVAL = "numeric", CNSR = "integer"
    )
  )
  for (dfTable in list(Synthetic_Results, Synthetic_Participants, Synthetic_Outcomes)) {
    expect_identical(class(dfTable), "data.frame")
    expect_identical(rownames(dfTable), as.character(seq_len(nrow(dfTable))))
  }
})

test_that("the participant table has one row per participant (#2)", {
  expect_identical(nrow(Synthetic_Participants), 200L)
  expect_false(anyDuplicated(Synthetic_Participants$USUBJID) > 0)
  expect_false(anyNA(Synthetic_Participants))

  expect_identical(
    as.list(table(Synthetic_Participants$ARM)),
    list(Placebo = 100L, Treatment = 100L)
  )
  expect_setequal(Synthetic_Participants$SEX, c("F", "M"))
  expect_setequal(Synthetic_Participants$RESPONSE, c("Responder", "Non-responder"))
  expect_true(all(Synthetic_Participants$AGE >= 18 & Synthetic_Participants$AGE <= 85))
  expect_true(all(Synthetic_Participants$BMIBL >= 16))
})

test_that("the results table has no duplicate participant, biomarker and visit (#2)", {
  expect_false(anyDuplicated(chrKey(Synthetic_Results, c("USUBJID", "TEST", "VISIT"))) > 0)

  expect_length(unique(Synthetic_Results$TEST), 12)
  expect_identical(
    unique(Synthetic_Results[order(Synthetic_Results$VISITNUM), "VISIT"]),
    c("Baseline", "Week 2", "Week 4", "Week 8", "Week 12")
  )
  # A visit has one visit order and a biomarker has one unit.
  expect_identical(nrow(unique(Synthetic_Results[c("VISIT", "VISITNUM")])), 5L)
  expect_identical(nrow(unique(Synthetic_Results[c("TEST", "STRESU")])), 12L)
  # Every result belongs to a participant in the participant table.
  expect_setequal(Synthetic_Results$USUBJID, Synthetic_Participants$USUBJID)
  expect_true(all(Synthetic_Results$STRESN > 0, na.rm = TRUE))
  # No character outside ASCII: the names travel through CSV into JavaScript.
  expect_false(any(grepl("[^ -~]", unlist(Synthetic_Results[c("VISIT", "TEST", "STRESU")]))))
})

test_that("the outcomes table has one row per participant and endpoint (#2)", {
  expect_false(anyDuplicated(chrKey(Synthetic_Outcomes, c("USUBJID", "PARAMCD"))) > 0)
  expect_identical(Synthetic_Outcomes$USUBJID, Synthetic_Participants$USUBJID)
  expect_identical(unique(Synthetic_Outcomes$PARAMCD), Synthetic_Truth$Survival$Endpoint)
  expect_length(unique(Synthetic_Outcomes$PARAM), 1)

  expect_false(anyNA(Synthetic_Outcomes))
  expect_true(all(Synthetic_Outcomes$AVAL > 0 & Synthetic_Outcomes$AVAL <= 24))
  expect_setequal(Synthetic_Outcomes$CNSR, c(0L, 1L))
})

test_that("the documented imperfections are present, and never at Baseline (#2)", {
  bBaseline <- Synthetic_Results$VISIT == "Baseline"

  # Baseline is complete: every participant, every biomarker, a value.
  expect_identical(sum(bBaseline), 200L * 12L)
  expect_false(anyNA(Synthetic_Results$STRESN[bBaseline]))

  # After Baseline some whole visits are missed, so their rows are absent ...
  nVisitsAttended <- nrow(unique(Synthetic_Results[!bBaseline, c("USUBJID", "VISIT")]))
  expect_lt(nVisitsAttended, 200L * 4L)
  expect_gt(nVisitsAttended, 200L * 4L * 0.9)
  # ... a visit attended has all twelve biomarkers ...
  expect_identical(sum(!bBaseline), nVisitsAttended * 12L)
  # ... and some results are present as rows with a missing value.
  nMissing <- sum(is.na(Synthetic_Results$STRESN))
  expect_gt(nMissing, 0)
  expect_lt(nMissing, sum(!bBaseline) * 0.05)
})

test_that("the truth list names the three planted effects in the terms they are estimated (#2)", {
  expect_named(Synthetic_Truth, c("Seed", "GroupDifference", "Correlation", "Survival"))

  lGroup <- Synthetic_Truth$GroupDifference
  expect_true(lGroup$Biomarker %in% Synthetic_Results$TEST)
  expect_true(all(c(lGroup$Visit, lGroup$BaselineVisit) %in% Synthetic_Results$VISIT))
  expect_setequal(Synthetic_Participants[[lGroup$GroupCol]], lGroup$Groups)
  expect_true(is.numeric(lGroup$Value) && lGroup$Value != 0)

  lCorrelation <- Synthetic_Truth$Correlation
  expect_true(all(lCorrelation$Biomarkers %in% Synthetic_Results$TEST))
  expect_true(lCorrelation$Visit %in% Synthetic_Results$VISIT)
  expect_identical(lCorrelation$Method, "pearson")
  expect_true(abs(lCorrelation$Value) > 0 && abs(lCorrelation$Value) < 1)

  lSurvival <- Synthetic_Truth$Survival
  expect_true(lSurvival$Biomarker %in% Synthetic_Results$TEST)
  expect_identical(lSurvival$Cut, "median")
  expect_identical(lSurvival$Groups, c("High", "Low"))
  expect_true(lSurvival$Value > 0 && lSurvival$Value != 1)

  # Each planted biomarker carries one effect only.
  expect_false(anyDuplicated(c(lGroup$Biomarker, lCorrelation$Biomarkers, lSurvival$Biomarker)) > 0)
})

test_that("the median split behind the planted survival effect is unambiguous (#2)", {
  lSurvival <- Synthetic_Truth$Survival
  nBaseline <- nResultAt(lSurvival$Biomarker, lSurvival$Visit)

  # No value sits on the median, so "above" and "at or above" give the same
  # two groups of one hundred.
  expect_false(anyNA(nBaseline))
  expect_false(any(nBaseline == stats::median(nBaseline)))
  expect_identical(sum(nBaseline > stats::median(nBaseline)), 100L)
})

test_that("base R recovers each planted effect inside its 95% interval (#2)", {
  lGroup <- Synthetic_Truth$GroupDifference
  nChange <- nResultAt(lGroup$Biomarker, lGroup$Visit) - nResultAt(lGroup$Biomarker, lGroup$BaselineVisit)
  chrArm <- Synthetic_Participants[[lGroup$GroupCol]]
  lWelch <- stats::t.test(nChange[chrArm == lGroup$Groups[1]], nChange[chrArm == lGroup$Groups[2]])
  expect_gt(lGroup$Value, lWelch$conf.int[1])
  expect_lt(lGroup$Value, lWelch$conf.int[2])
  expect_lt(lWelch$p.value, 0.001)

  lCorrelation <- Synthetic_Truth$Correlation
  lPearson <- stats::cor.test(
    nResultAt(lCorrelation$Biomarkers[1], lCorrelation$Visit),
    nResultAt(lCorrelation$Biomarkers[2], lCorrelation$Visit),
    method = lCorrelation$Method
  )
  expect_gt(lCorrelation$Value, lPearson$conf.int[1])
  expect_lt(lCorrelation$Value, lPearson$conf.int[2])
  expect_lt(lPearson$p.value, 0.001)

  lSurvival <- Synthetic_Truth$Survival
  nBaseline <- nResultAt(lSurvival$Biomarker, lSurvival$Visit)
  dfCox <- data.frame(
    AVAL = Synthetic_Outcomes$AVAL,
    Event = Synthetic_Outcomes$CNSR == 0,
    High = nBaseline > stats::median(nBaseline)
  )
  lCox <- summary(survival::coxph(survival::Surv(AVAL, Event) ~ High, data = dfCox))
  expect_gt(lSurvival$Value, lCox$conf.int[1, "lower .95"])
  expect_lt(lSurvival$Value, lCox$conf.int[1, "upper .95"])
  expect_lt(lCox$coefficients[1, "Pr(>|z|)"], 0.001)
})

test_that("the help pages name each planted effect and its true size (#2)", {
  lGroup <- Synthetic_Truth$GroupDifference
  lCorrelation <- Synthetic_Truth$Correlation
  lSurvival <- Synthetic_Truth$Survival

  strResults <- strHelpText("Synthetic_Results")
  expect_match(strResults, lGroup$Biomarker, fixed = TRUE)
  expect_match(strResults, paste0(format(abs(lGroup$Value)), " ", "pg/mL"), fixed = TRUE)
  expect_match(strResults, lCorrelation$Biomarkers[1], fixed = TRUE)
  expect_match(strResults, lCorrelation$Biomarkers[2], fixed = TRUE)
  expect_match(strResults, paste("correlation of", format(lCorrelation$Value)), fixed = TRUE)
  expect_match(strResults, paste(nrow(Synthetic_Results), "rows"), fixed = TRUE)

  strOutcomes <- strHelpText("Synthetic_Outcomes")
  expect_match(strOutcomes, lSurvival$Biomarker, fixed = TRUE)
  expect_match(strOutcomes, paste("hazard ratio of", format(lSurvival$Value)), fixed = TRUE)

  strParticipants <- strHelpText("Synthetic_Participants")
  expect_match(strParticipants, paste(nrow(Synthetic_Participants), "rows"), fixed = TRUE)

  strTruth <- strHelpText("Synthetic_Truth")
  for (nValue in c(lGroup$Value, lCorrelation$Value, lSurvival$Value)) {
    expect_match(strTruth, format(nValue), fixed = TRUE)
  }
  expect_match(strTruth, format(Synthetic_Truth$Seed), fixed = TRUE)
})

test_that("the CSV files under inst/extdata equal the package data (#2)", {
  ReadTable <- function(strName, chrClasses) {
    strPath <- system.file("extdata", paste0("synthetic_", strName, ".csv"), package = "gsm.bio")
    expect_true(nzchar(strPath), label = paste0("synthetic_", strName, ".csv is installed"))
    # The classes are stated, not guessed: an empty field is a missing number,
    # and an identifier is never read as one.
    utils::read.csv(strPath, colClasses = chrClasses, na.strings = "", stringsAsFactors = FALSE)
  }

  expect_identical(
    ReadTable("results", c("character", "character", "integer", "character", "character", "numeric")),
    Synthetic_Results
  )
  expect_identical(
    ReadTable("participants", c("character", "character", "character", "integer", "numeric", "character")),
    Synthetic_Participants
  )
  expect_identical(
    ReadTable("outcomes", c("character", "character", "character", "numeric", "integer")),
    Synthetic_Outcomes
  )
})

test_that("rerunning the script gives identical tables and identical CSV files (#2)", {
  # data-raw/ is not part of the built package, so this runs in the source tree
  # (devtools::test() and CI's source-tree step) and skips under R CMD check.
  skip_if_not(bSourceTree(), "data-raw/ is not part of the built package")
  strScript <- file.path(strSourceRoot(), "data-raw", "synthetic-study.R")
  expect_true(file.exists(strScript))

  strOut <- tempfile("synthetic-study-")
  dir.create(strOut)
  on.exit(unlink(strOut, recursive = TRUE))
  envScript <- new.env(parent = globalenv())
  assign("strOutputRoot", strOut, envir = envScript)
  nSeedBefore <- get0(".Random.seed", envir = globalenv())
  sys.source(strScript, envir = envScript)
  # The script pins its own generator and puts the session's back.
  expect_identical(get0(".Random.seed", envir = globalenv()), nSeedBefore)

  for (strName in c("Synthetic_Results", "Synthetic_Participants", "Synthetic_Outcomes", "Synthetic_Truth")) {
    envData <- new.env()
    load(file.path(strOut, "data", paste0(strName, ".rda")), envir = envData)
    expect_identical(ls(envData), strName)
    expect_identical(envData[[strName]], getExportedValue("gsm.bio", strName), label = strName)
  }

  for (strFile in paste0("synthetic_", c("results", "participants", "outcomes"), ".csv")) {
    expect_identical(
      readLines(file.path(strOut, "inst", "extdata", strFile)),
      readLines(file.path(strSourceRoot(), "inst", "extdata", strFile)),
      label = strFile
    )
  }
})
