#' Synthetic biomarker study: results
#'
#' Biomarker results for a made-up study of 200 participants, twelve biomarkers
#' and five visits, with one row per participant, biomarker and visit. It is the
#' one table every biomarker chart needs, and it exists so that a test can
#' assert an answer that is known in advance.
#'
#' Everything in it is synthetic. The values are random draws from the model in
#' the script `data-raw/synthetic-study.R`, run with the seed recorded in
#' [Synthetic_Truth]. No real study data was used and nothing was copied from
#' any real study; the biomarker names are generic analyte names, with levels
#' chosen only to look plausible.
#'
#' @section Planted effects:
#' Two of the three planted effects are in this table. Their true sizes are
#' parameters of the generating model, held in [Synthetic_Truth].
#'
#' * **A difference between two groups in change from baseline.** In the
#'   Treatment arm, IL-6 is lower by 1.5 pg/mL at every visit after Baseline. So
#'   the difference between the arms in mean change from Baseline, Treatment
#'   minus Placebo, is -1.5 pg/mL at each of Week 2, Week 4, Week 8 and
#'   Week 12. The arms do not differ at Baseline.
#' * **A correlation between two biomarkers.** TNF-alpha and IL-10 are drawn
#'   from a bivariate normal distribution with a Pearson correlation of 0.6 at
#'   each visit, on the scale stored here.
#'
#' The third, a survival difference between high and low Baseline CRP, is in
#' [Synthetic_Outcomes]. Every other biomarker is null by construction:
#' unrelated to arm, to every other biomarker and to the outcome. Each planted
#' biomarker carries its one effect only.
#'
#' The true sizes describe the model before the stored values were rounded to
#' three decimal places, which moves none of them by an amount a test can see.
#'
#' @section Model:
#' Each biomarker has a participant-level part, 60 percent of its variance, and
#' a visit-level part. IL-6, TNF-alpha, IL-10, IL-2, IL-1beta, VEGF and LDH are
#' normal on the stored scale; CRP, IFN-gamma, IL-8, Ferritin and D-dimer are
#' log-normal, so right-skewed.
#'
#' @section Imperfections:
#' Baseline is complete: every participant has all twelve biomarkers. After
#' Baseline, two things are missing completely at random, as they would be in
#' a real study, so that a chart has dropped rows to count:
#'
#' * a participant misses a whole visit with probability 0.05, and that visit
#'   has no rows at all;
#' * a result is not analysable with probability 0.02, and its row is present
#'   with a missing `STRESN`.
#'
#' @format A data frame with 11472 rows and 6 columns. The column names are the
#'   defaults safety.viz uses for results data.
#' \describe{
#'   \item{USUBJID}{`character` Participant identifier, `BIO-001` to `BIO-200`.}
#'   \item{VISIT}{`character` Visit name: `Baseline`, `Week 2`, `Week 4`, `Week 8` or `Week 12`.}
#'   \item{VISITNUM}{`integer` Visit order, the week number: 0, 2, 4, 8 or 12.}
#'   \item{TEST}{`character` Biomarker name, in ASCII: `IL-6`, `CRP`, `TNF-alpha`,
#'     `IL-10`, `IFN-gamma`, `IL-2`, `IL-1beta`, `IL-8`, `VEGF`, `Ferritin`,
#'     `D-dimer` or `LDH`.}
#'   \item{STRESU}{`character` Unit of the result.}
#'   \item{STRESN}{`numeric` Result, to three decimal places; missing where a
#'     sample was not analysable.}
#' }
#'
#' @source Generated by `data-raw/synthetic-study.R`. The same table is in the
#'   package as `system.file("extdata", "synthetic_results.csv", package = "gsm.bio")`.
#' @seealso [Synthetic_Participants], [Synthetic_Outcomes], [Synthetic_Truth]
"Synthetic_Results"

#' Synthetic biomarker study: participants
#'
#' One row per participant of the made-up study in [Synthetic_Results]: the
#' treatment arm, and the participant-level variables a chart can group, panel
#' or filter by.
#'
#' Everything in it is synthetic. Arm is the grouping behind the planted
#' difference in IL-6 (see [Synthetic_Results]). The other columns are drawn
#' independently of each other, of arm, of every biomarker and of the outcome,
#' so any association a test finds with them is chance.
#'
#' @format A data frame with 200 rows and 6 columns. The names follow ADaM's
#'   subject-level dataset where it has one.
#' \describe{
#'   \item{USUBJID}{`character` Participant identifier, `BIO-001` to `BIO-200`.}
#'   \item{ARM}{`character` Treatment arm, `Placebo` or `Treatment`, 100 participants each.}
#'   \item{SEX}{`character` `F` or `M`.}
#'   \item{AGE}{`integer` Age in years, 18 to 85.}
#'   \item{BMIBL}{`numeric` Body mass index at baseline in kg/m2, to one decimal
#'     place: the continuous baseline characteristic.}
#'   \item{RESPONSE}{`character` `Responder` or `Non-responder`.}
#' }
#'
#' @source Generated by `data-raw/synthetic-study.R`. The same table is in the
#'   package as `system.file("extdata", "synthetic_participants.csv", package = "gsm.bio")`.
#' @seealso [Synthetic_Results], [Synthetic_Outcomes], [Synthetic_Truth]
"Synthetic_Participants"

#' Synthetic biomarker study: outcomes
#'
#' One row per participant and endpoint of the made-up study in
#' [Synthetic_Results], with a time and a censor flag. There is one endpoint,
#' event-free survival in months.
#'
#' Everything in it is synthetic: the times are random draws, not observations.
#'
#' @section Planted effect:
#' Participants are split at the median of their Baseline CRP in
#' [Synthetic_Results], 100 above it and 100 below, with no value on the
#' median. Event times are exponential, and the hazard in the high group is
#' the hazard in the low group multiplied by a constant: a hazard ratio of 2.5,
#' high against low. CRP has no other relationship with the outcome, and no
#' other biomarker has any.
#'
#' Censoring is independent of the event: a participant drops out at an
#' exponential time, and follow-up ends at 24 months. The true hazard ratio is
#' a parameter of the generating model, held in [Synthetic_Truth].
#'
#' @format A data frame with 200 rows and 5 columns. The names are ADaM's
#'   time-to-event names.
#' \describe{
#'   \item{USUBJID}{`character` Participant identifier, `BIO-001` to `BIO-200`.}
#'   \item{PARAMCD}{`character` Endpoint code, `EFS`.}
#'   \item{PARAM}{`character` Endpoint name, `Event-free survival (months)`.}
#'   \item{AVAL}{`numeric` Time to the event or to censoring, in months, to two
#'     decimal places.}
#'   \item{CNSR}{`integer` Censor flag, ADaM's way round: 0 for an event, 1 for a
#'     censored time.}
#' }
#'
#' @source Generated by `data-raw/synthetic-study.R`. The same table is in the
#'   package as `system.file("extdata", "synthetic_outcomes.csv", package = "gsm.bio")`.
#' @seealso [Synthetic_Results], [Synthetic_Participants], [Synthetic_Truth]
"Synthetic_Outcomes"

#' Synthetic biomarker study: the planted effects and their true sizes
#'
#' The three effects planted in the synthetic study, each with its true size.
#' This list is the generator's own parameter list: the script
#' `data-raw/synthetic-study.R` read these values to make the data, so a test
#' that asserts against them asserts against the truth and not a copy of it.
#'
#' Each true size is an exact parameter of the generating model, stated in the
#' terms the matching statistic estimates:
#'
#' | Effect | Where | Truth |
#' |---|---|---|
#' | Difference in mean change from Baseline, Treatment minus Placebo | IL-6, at each visit after Baseline | -1.5 pg/mL |
#' | Pearson correlation | TNF-alpha and IL-10, at each visit | 0.6 |
#' | Hazard ratio, high against low | Baseline CRP split at its median, event-free survival | 2.5 |
#'
#' Every other biomarker is null by construction. The study was generated once,
#' with seed 364, and each truth lies inside the 95 percent interval base R
#' computes from the data.
#'
#' @format A list of four:
#' \describe{
#'   \item{Seed}{`integer` The seed the study was generated with.}
#'   \item{GroupDifference}{A list: `Biomarker`; `Visit`, the visit tests use,
#'     and `BaselineVisit`; `GroupCol`, the column of [Synthetic_Participants]
#'     that holds the groups; `Groups`, in the order of the subtraction;
#'     `Estimand`, in words; and `Value`, the true difference.}
#'   \item{Correlation}{A list: `Biomarkers`, the pair; `Visit`, the visit tests
#'     use; `Method`, `"pearson"`; `Estimand`; and `Value`, the true coefficient.}
#'   \item{Survival}{A list: `Biomarker`; `Visit`; `Cut`, `"median"`; `Groups`,
#'     numerator first; `Endpoint`, the `PARAMCD` in [Synthetic_Outcomes];
#'     `Estimand`; and `Value`, the true hazard ratio.}
#' }
#'
#' @source Written by `data-raw/synthetic-study.R`.
#' @seealso [Synthetic_Results], [Synthetic_Participants], [Synthetic_Outcomes]
"Synthetic_Truth"
